name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Cache Cargo dependencies
        uses: actions/cache@v2.1.4
        with:
          path: /usr/share/rust
          key: ${{ runner.OS }}-cargo-cache

      - name: Get "broken-md-links" tool
        run: cargo install broken-md-links

      - name: Get "mdBook" tool
        run: cargo install mdbook

      - name: Look for broken markdown links
        run: broken-md-links ${GITHUB_WORKSPACE}/docs --recursive

      - name: Build the docs
        run: mdbook build

      - name: Deploy the docs
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: book
