name: docs

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache Cargo dependencies
        uses: actions/cache@v2.1.3
        with:
          path: /usr/share/rust
          key: ${{ runner.OS }}-cargo-cache

      - name: Get "broken-md-links" tool
        run: cargo install broken-md-links

      - name: Get "mdBook" tool
        run: cargo install mdbook

      - name: Look for broken markdown links
        run: broken-md-links ${GITHUB_WORKSPACE}/docs --recursive

      - name: Build the docs
        run: mdbook build

      - name: Deploy the docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: book
          CLEAN: true
