name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
        with:
          persist-credentials: false

      - name: Install "cargo-binstall"
        uses: cargo-bins/cargo-binstall@install-cargo-binstall-1.0.0

      - name: Install "broken-md-links"
        run: cargo binstall "broken-md-links" -y

      - name: Check docs
        run: broken-md-links ${GITHUB_WORKSPACE}/docs --recursive
        
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1.2.0
        with:
          mdbook-version: latest

      - name: Build the docs
        run: mdbook build

      - name: Deploy the docs
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: book
