name: CI

on: [push]

jobs:
  check-broken-md-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Cargo dependencies
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cargo
          key: cargo-data
      - name: Get "broken-md-links"  tool
        run: cargo install broken-md-links
      - name: Look for broken MD links
        run: broken-md-links ${GITHUB_WORKSPACE}/docs --recursive
